baseURL = "www.autoug.io"
languageCode = "en-us"
title = "Automation User Group"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "Automation User Group"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = false

#[[menu.main]]
#  name = "External"
#  url = "https://example.com"

[social]
#  facebook = "https://facebook.com"
  twitter = "https://twitter.com/automationug"
#  instagram = "https://instagram.com"
#  linkedin = "https://linkedin.com"